const nutritionalConsultationsMock = {
  recyQ18J6D6fEPqcn: {
    Member: ['memberRecordID'],
    'Do you have any of the following conditions?': [
      'High Blood Pressure',
      'Overweight',
      'High Cholesterol',
      'Diabetes',
    ],
    Breakfast: '1 bowl of Oatbix cereals + 1 banana + soy milk\n',
    Lunch:
      'Vegetables - french beans, carrots, cauliflower + 2 brown chapati\n',
    Dinner:
      '1 scoop of brown rice/chapati + 1/4 plate meat curry + 1/2 plate sukuma/spinach\n',
    Snacks: 'Mid-day snack: Orange\nEvening snack: Banana\n',
    'How many glasses of water do you take in a day?': 6,
    'High Salt Foods (Packaged salty snacks like crisps, salted nuts, popcorn or salty biscuits/crackers)': 0,
    'High Salt Foods (Cold Cuts or Processed Meats like sausage, bacon, ham, or smokie)': 0.2,
    'High Salt Foods (Fast food like chips, bhajia, pizza, deep-fried chicken, or cheesy foods)': 0,
    'High Salt Foods (Canned foods like baked beans, maize, corn, peas, or tomatoes)': 0,
    'High Salt Foods (Condiments like tomato sauce, ketchup, chili sauce or mustard)': 0,
    'High Salt Foods (Seasoning like Royco, Maggi cubes, Soy sauce, Tomato Paste)': 4,
    'High Salt Foods (Table Salt)': 0,
    'Is salt added to your food when cooked?': 'Minimal',
    'High Potassium Foods (Dark green leafy or traditional/kienyeji vegetables)': 14,
    'High Potassium Foods (Ripe bananas)': 7,
    'High Potassium Foods (Cooked plantains/ green bananas)': 0,
    'High Potassium Foods (Unsalted nuts)': 0,
    'High Potassium Foods (Root vegetables like beetroot, sweet potatoes, arrow roots or yams)': 0.2,
    'Basal Metabolic Rate': 1769,
    'Estimated Caloric Needs': 2000,
    'Estimated Daily Caloric Intake': 2200,
    'Breakfast Glycemic Load': 25,
    'Lunch Glycemic Load': 26,
    'Snacks Glycemic Load': 10,
    'Dinner Glycemic Load': 35,
    'Total Daily Glycemic Load': 96,
    Eggs: 0,
    'Deep Fried': 0.2,
    'Fast Food': 0,
    'Cold Cuts': 0,
    'Daily estimated cholesterol intake': 67,
    Assessment:
      "LEVEL 1 SODIUM INTAKE (normal). She can do better in salt reduction by not using seasoning like Royco while cooking. She eats sausages once in a while if her son brings them. \nLEVEL 1 POTASSIUM INTAKE (normal). She loves fruits and vegetables and her intake is okay.\nLEVEL 0 CHOLESTEROL INTAKE (recommended). She does not eat fatty parts of meat & always removes poultry skin. No use of solid fats & eats 2 boiled (egg whites only) per week.\nSlightly higher caloric intake. High triglycerides also show that her kcals aren't utilized immediately. Her plate portions are great.\nLEVEL 1 GLYCEMIC LOAD (normal), ie <100.\n",
    Recommendation:
      'Dietary milestones: <1500 mg sodium/day, maintain a 2000 kcal diet and increase her activity levels.\n',
    'Put anything else you want to share here!':
      'Reports lower appetite, thus eating smaller portions of food. BP often gets high due to stress (149 SYS) gets high before b/fast. Advised to add more food sources of unsaturated fats such as nuts, fish and soy products.\n',
    'Basal Daily Sodium': 2000,
    'Basal Daily Potassium': 1100,
    'Date of Consultation': '2020-08-07',
    'Nutritional Consultation #': 2,
    created_at: '2020-08-07T09:32:00.000Z',
    ID: ['HKP-FQN3'],
    'Weekly Sodium - Canned Foods': 0,
    'Weekly Sodium - Meats': 188,
    'Weekly Sodium - Snacks': 0,
    'Weekly Sodium - Fast Food': 0,
    'Weekly Sodium - Table Salt': 0,
    'Weekly Sodium - Condiments': 0,
    'Weekly Sodium - Seasonings': 2120,
    'Calculated Estimated Daily Sodium': 2329.714285714286,
    'Weekly Potassium - Leafy Greens': 8260,
    'Weekly Potassium - Bannanas': 2730,
    'Weekly Potassium - Plantains': 0,
    'Weekly Potassium - Nuts': 0,
    'Weekly Potassium - roots': 142,
    'Calculated Daily Potassium': 2690.285714285714,
    'Member Record ID': ['memberRecordID'],
    HN: ['recRpK8ZZVLBHKuye'],
    Summary: 'Test Peter Mwangi - Test Health Navigator',
  },
  recbNbhsfWQAFCkLO: {
    Member: ['memberRecordID'],
    'Do you have any of the following conditions?': [
      'Overweight',
      'High Blood Pressure',
      'Other',
      'Diabetes',
    ],
    Assessment:
      'Nutrition call: she agreed to fill in a food diary for 3 days (Fri-Sun) for a better nutrition review during the baseline assessment on Monday. She was taken through the process, methods & importance of filling in a food diary. She gave an account of what she has eaten today so far -this also served as an example of how to quantify food when filling in the diary. It was agreed that she will be sending photos or texts of what she has eaten.\n',
    'Describe Other Condition': 'Varicose veins',
    'Date of Consultation': '2020-02-21',
    'Nutritional Consultation #': 1,
    created_at: '2020-08-16T12:56:21.000Z',
    ID: ['HKP-FQN3'],
    'Weekly Sodium - Canned Foods': 0,
    'Weekly Sodium - Meats': 0,
    'Weekly Sodium - Snacks': 0,
    'Weekly Sodium - Fast Food': 0,
    'Weekly Sodium - Table Salt': 0,
    'Weekly Sodium - Condiments': 0,
    'Weekly Sodium - Seasonings': 0,
    'Calculated Estimated Daily Sodium': 0,
    'Weekly Potassium - Leafy Greens': 0,
    'Weekly Potassium - Bannanas': 0,
    'Weekly Potassium - Plantains': 0,
    'Weekly Potassium - Nuts': 0,
    'Weekly Potassium - roots': 0,
    'Calculated Daily Potassium': 0,
    'Member Record ID': ['memberRecordID'],
    HN: ['recRpK8ZZVLBHKuye'],
    Summary: 'Test Peter Mwangi - Test Health Navigator',
  },
}

export default nutritionalConsultationsMock
