const tasks_mock_response = {
  reckDDIH5ccKXJIVQ: {
    Type: 'Rx: Refill',
    Member: ['member_record_id'],
    'Due Date': '2020-08-19',
    'Task Notes':
      'medication Logistics and Refill for 3 days notice prior to refill date',
    Assignee: ['assigned_hn'],
    Status: 'Not Started',
    'Task Priority': 'High',
    'Auto Generated': true,
    Prescription: ['recoQhIzfwhLfudws'],
    'Form URL':
      'https://airtable.com/tbl3iBWzYVWEpdLje/viwZ1H1vBNJVMmpBJ?blocks=hide',
    Name: 'Rx: Refill (Test Bene)',
    created_at: '2020-08-16T00:09:42.000Z',
    last_modified: '2020-08-16T00:09:42.000Z',
    'HN (from Members)': ['assigned_hn'],
    'Last Status changed at': '2020-08-16T00:09:42.000Z',
    'HN Slack ID': ['slack_id'],
    'Antara ID': ['antara_id'],
    'Send SMS': {
      label: 'Send SMS',
      url:
        'https://airtable.com/table_id/reckDDIH5ccKXJIVQ?blocks=blisrVqe2tDu2aEra',
    },
    recordid: 'reckDDIH5ccKXJIVQ',
    'Open URL': {
      label: 'Open URL',
      url:
        'https://airtable.com/tbl3iBWzYVWEpdLje/viwZ1H1vBNJVMmpBJ?blocks=hide',
    },
    member_record_id: ['member_record_id'],
    'Dashboard URL': {
      label: 'Open Dashboard ',
      url: 'https://hn-dashboard.herokuapp.com/member/member_record_id',
    },
    'Days overdue': 20,
    'Member Record ID': ['member_record_id'],
    'Assigned HN Name': ["Anne Esang'ire"],
    member_status: ['Active'],
  },
  recuvlfaovtO75aRV: {
    Type: 'Rx: Followup',
    Member: ['member_record_id'],
    'Due Date': '2020-08-17',
    'Task Notes':
      "It's 5 days to refill date.\n\nFollowup to confirm the medication quantity at hand and any other prevailing issue in anticipation of next refill",
    Assignee: ['assigned_hn'],
    Status: 'Complete',
    'Task Priority': 'Medium',
    'Auto Generated': true,
    Prescription: ['recoQhIzfwhLfudws'],
    'Form URL':
      'https://airtable.com/shrKQ5efAEh9z3618?prefill_Member=member_record_id&prefill_Health Navigator=assigned_hn',
    Name: 'Rx: Followup (Test Bene)',
    created_at: '2020-08-16T00:09:41.000Z',
    last_modified: '2020-08-21T11:07:29.000Z',
    'HN (from Members)': ['assigned_hn'],
    'Last Status changed at': '2020-08-21T11:07:29.000Z',
    'HN Slack ID': ['slack_id'],
    'Antara ID': ['antara_id'],
    'Send SMS': {
      label: 'Send SMS',
      url:
        'https://airtable.com/table_id/recuvlfaovtO75aRV?blocks=blisrVqe2tDu2aEra',
    },
    recordid: 'recuvlfaovtO75aRV',
    'Open URL': {
      label: 'Open URL',
      url:
        'https://airtable.com/shrKQ5efAEh9z3618?prefill_Member=member_record_id&prefill_Health Navigator=assigned_hn',
    },
    member_record_id: ['member_record_id'],
    'Dashboard URL': {
      label: 'Open Dashboard ',
      url: 'https://hn-dashboard.herokuapp.com/member/member_record_id',
    },
    'Days overdue': 22,
    'Member Record ID': ['member_record_id'],
    'Assigned HN Name': ["Anne Esang'ire"],
    member_status: ['Active'],
  },
  recXQFem8QcXgldWk: {
    Type: 'Rx: Followup',
    Member: ['member_record_id'],
    'Due Date': '2020-07-26',
    'Task Notes':
      'Followup on medication treatment 3 days after prescription.\nMedications: ',
    Assignee: ['assigned_hn'],
    Status: 'Complete',
    'Task Priority': 'Medium',
    'Auto Generated': true,
    Prescription: ['recoQhIzfwhLfudws'],
    Name: 'Rx: Followup (Test Bene)',
    created_at: '2020-07-24T21:08:14.000Z',
    last_modified: '2020-08-21T11:06:18.000Z',
    'HN (from Members)': ['assigned_hn'],
    'Last Status changed at': '2020-08-21T11:06:18.000Z',
    'HN Slack ID': ['slack_id'],
    'Antara ID': ['antara_id'],
    'Send SMS': {
      label: 'Send SMS',
      url:
        'https://airtable.com/table_id/recXQFem8QcXgldWk?blocks=blisrVqe2tDu2aEra',
    },
    recordid: 'recXQFem8QcXgldWk',
    'Open URL': { label: 'Open URL', url: '' },
    member_record_id: ['member_record_id'],
    'Dashboard URL': {
      label: 'Open Dashboard ',
      url: 'https://hn-dashboard.herokuapp.com/member/member_record_id',
    },
    'Days overdue': 44,
    'Member Record ID': ['member_record_id'],
    'Assigned HN Name': ["Anne Esang'ire"],
    member_status: ['Active'],
  },
  recAaomkOYGAHzyEA: {
    Type: 'Rx: Refill',
    Member: ['member_record_id'],
    'Due Date': '2020-07-22',
    'Task Notes':
      'medication Logistics and Refill for 3 days notice prior to refill date',
    Assignee: ['assigned_hn'],
    Status: 'Complete',
    'Task Priority': 'High',
    'Auto Generated': true,
    Name: 'Rx: Refill (Test Bene)',
    created_at: '2020-07-19T00:04:15.000Z',
    last_modified: '2020-08-03T10:00:47.000Z',
    'HN (from Members)': ['assigned_hn'],
    'Last Status changed at': '2020-08-03T10:00:47.000Z',
    'HN Slack ID': ['slack_id'],
    'Antara ID': ['antara_id'],
    'Send SMS': {
      label: 'Send SMS',
      url:
        'https://airtable.com/table_id/recAaomkOYGAHzyEA?blocks=blisrVqe2tDu2aEra',
    },
    recordid: 'recAaomkOYGAHzyEA',
    'Open URL': { label: 'Open URL', url: '' },
    member_record_id: ['member_record_id'],
    'Dashboard URL': {
      label: 'Open Dashboard ',
      url: 'https://hn-dashboard.herokuapp.com/member/member_record_id',
    },
    'Days overdue': 48,
    'Member Record ID': ['member_record_id'],
    'Assigned HN Name': ["Anne Esang'ire"],
    member_status: ['Active'],
  },
  recdGIIIGbrdd08z5: {
    Type: 'Rx: Followup',
    Member: ['member_record_id'],
    'Due Date': '2020-07-20',
    'Task Notes':
      "It's 5 days to refill date.\n\nFollowup to confirm the medication quantity at hand and any other prevailing issue in anticipation of next refill",
    Assignee: ['assigned_hn'],
    Status: 'Complete',
    'Task Priority': 'Medium',
    'Auto Generated': true,
    Name: 'Rx: Followup (Test Bene)',
    created_at: '2020-07-19T00:04:14.000Z',
    last_modified: '2020-07-22T15:57:25.000Z',
    'HN (from Members)': ['assigned_hn'],
    'Last Status changed at': '2020-07-22T15:57:25.000Z',
    'HN Slack ID': ['slack_id'],
    'Antara ID': ['antara_id'],
    'Send SMS': {
      label: 'Send SMS',
      url:
        'https://airtable.com/table_id/recdGIIIGbrdd08z5?blocks=blisrVqe2tDu2aEra',
    },
    recordid: 'recdGIIIGbrdd08z5',
    'Open URL': { label: 'Open URL', url: '' },
    member_record_id: ['member_record_id'],
    'Dashboard URL': {
      label: 'Open Dashboard ',
      url: 'https://hn-dashboard.herokuapp.com/member/member_record_id',
    },
    'Days overdue': 50,
    'Member Record ID': ['member_record_id'],
    'Assigned HN Name': ["Anne Esang'ire"],
    member_status: ['Active'],
  },
  recXB09w92oOPaEe2: {
    Type: 'Rx: Followup',
    Member: ['member_record_id'],
    'Due Date': '2020-07-13',
    'Task Notes':
      'Followup on medication treatment 3 days after prescription.\nMedications: ',
    Assignee: ['assigned_hn'],
    Status: 'Complete',
    'Task Priority': 'Medium',
    Name: 'Rx: Followup (Test Bene)',
    created_at: '2020-07-11T21:05:28.000Z',
    last_modified: '2020-08-21T11:05:53.000Z',
    'HN (from Members)': ['assigned_hn'],
    'Last Status changed at': '2020-08-21T11:05:53.000Z',
    'HN Slack ID': ['slack_id'],
    'Antara ID': ['antara_id'],
    'Send SMS': {
      label: 'Send SMS',
      url:
        'https://airtable.com/table_id/recXB09w92oOPaEe2?blocks=blisrVqe2tDu2aEra',
    },
    recordid: 'recXB09w92oOPaEe2',
    'Open URL': { label: 'Open URL', url: '' },
    member_record_id: ['member_record_id'],
    'Dashboard URL': {
      label: 'Open Dashboard ',
      url: 'https://hn-dashboard.herokuapp.com/member/member_record_id',
    },
    'Days overdue': 57,
    'Member Record ID': ['member_record_id'],
    'Assigned HN Name': ["Anne Esang'ire"],
    member_status: ['Active'],
  },
  recNP6CNEmfGoM5Ei: {
    Type: 'Schedule Avenue visit',
    Member: ['member_record_id'],
    'Due Date': '2020-06-16',
    'Task Notes':
      'Schedule for her consultation with DR Momina tomorrow the 16th of june',
    Assignee: ['recRpK8ZZVLBHKuye'],
    Status: 'Complete',
    'Task Priority': 'High',
    Name: 'Schedule Avenue visit (Test Bene)',
    created_at: '2020-06-15T11:17:22.000Z',
    last_modified: '2020-07-24T09:57:50.000Z',
    'HN (from Members)': ['assigned_hn'],
    'Last Status changed at': '2020-06-15T19:14:58.000Z',
    'HN Slack ID': ['UFPUVDZCZ'],
    'Antara ID': ['antara_id'],
    'Send SMS': {
      label: 'Send SMS',
      url:
        'https://airtable.com/table_id/recNP6CNEmfGoM5Ei?blocks=blisrVqe2tDu2aEra',
    },
    recordid: 'recNP6CNEmfGoM5Ei',
    'Open URL': { label: 'Open URL', url: '' },
    member_record_id: ['member_record_id'],
    'Dashboard URL': {
      label: 'Open Dashboard ',
      url: 'https://hn-dashboard.herokuapp.com/member/member_record_id',
    },
    'Days overdue': 84,
    'Member Record ID': ['member_record_id'],
    'Assigned HN Name': ['Rebecca Nyakundi'],
    member_status: ['Active'],
  },
  recBUjKjohSwNpxLd: {
    Type: 'Schedule Avenue visit',
    Member: ['member_record_id'],
    'Due Date': '2020-06-08',
    'Task Notes': 'Confirm her rescheduled meeting with Dr Momina ',
    Assignee: ['assigned_hn'],
    Status: 'Complete',
    'Task Priority': 'High',
    Name: 'Schedule Avenue visit (Test Bene)',
    created_at: '2020-06-09T07:01:37.000Z',
    last_modified: '2020-06-29T06:32:45.000Z',
    'HN (from Members)': ['assigned_hn'],
    'Last Status changed at': '2020-06-12T18:08:45.000Z',
    'HN Slack ID': ['slack_id'],
    'Antara ID': ['antara_id'],
    'Send SMS': {
      label: 'Send SMS',
      url:
        'https://airtable.com/table_id/recBUjKjohSwNpxLd?blocks=blisrVqe2tDu2aEra',
    },
    recordid: 'recBUjKjohSwNpxLd',
    'Open URL': { label: 'Open URL', url: '' },
    member_record_id: ['member_record_id'],
    'Dashboard URL': {
      label: 'Open Dashboard ',
      url: 'https://hn-dashboard.herokuapp.com/member/member_record_id',
    },
    'Days overdue': 92,
    'Member Record ID': ['member_record_id'],
    'Assigned HN Name': ["Anne Esang'ire"],
    member_status: ['Active'],
  },
  recpvJqArwF49iXGS: {
    Type: 'Schedule: Followup call',
    Member: ['member_record_id'],
    'Due Date': '2020-05-28',
    'Task Notes':
      'Call post virtual consultation with the physician later today',
    Assignee: ['assigned_hn'],
    Status: 'Complete',
    Name: 'Schedule: Followup call (Test Bene)',
    created_at: '2020-06-03T05:12:58.000Z',
    last_modified: '2020-06-29T06:32:45.000Z',
    'HN (from Members)': ['assigned_hn'],
    'Last Status changed at': '2020-06-03T05:12:58.000Z',
    'HN Slack ID': ['slack_id'],
    'Antara ID': ['antara_id'],
    'Send SMS': {
      label: 'Send SMS',
      url:
        'https://airtable.com/table_id/recpvJqArwF49iXGS?blocks=blisrVqe2tDu2aEra',
    },
    recordid: 'recpvJqArwF49iXGS',
    'Open URL': { label: 'Open URL', url: '' },
    member_record_id: ['member_record_id'],
    'Dashboard URL': {
      label: 'Open Dashboard ',
      url: 'https://hn-dashboard.herokuapp.com/member/member_record_id',
    },
    'Days overdue': 103,
    'Member Record ID': ['member_record_id'],
    'Assigned HN Name': ["Anne Esang'ire"],
    member_status: ['Active'],
  },
  recRxRwuISMa7AOnK: {
    Type: 'Schedule: Avenue visit',
    Member: ['member_record_id'],
    'Due Date': '2020-05-14',
    'Task Notes':
      'follow up for appointment scheduling, diet plan follow up  and also suggest on other physical activities ',
    Assignee: ['assigned_hn'],
    Status: 'On Hold',
    Name: 'Schedule: Avenue visit (Test Bene)',
    created_at: '2020-06-03T05:13:06.000Z',
    last_modified: '2020-06-29T06:32:45.000Z',
    'HN (from Members)': ['assigned_hn'],
    'Last Status changed at': '2020-06-03T05:13:06.000Z',
    'HN Slack ID': ['slack_id'],
    'Antara ID': ['antara_id'],
    'Send SMS': {
      label: 'Send SMS',
      url:
        'https://airtable.com/table_id/recRxRwuISMa7AOnK?blocks=blisrVqe2tDu2aEra',
    },
    recordid: 'recRxRwuISMa7AOnK',
    'Open URL': { label: 'Open URL', url: '' },
    member_record_id: ['member_record_id'],
    'Dashboard URL': {
      label: 'Open Dashboard ',
      url: 'https://hn-dashboard.herokuapp.com/member/member_record_id',
    },
    'Days overdue': 117,
    'Member Record ID': ['member_record_id'],
    'Assigned HN Name': ["Anne Esang'ire"],
    member_status: ['Active'],
  },
}

export default tasks_mock_response
