const TABLE_ROUTES = {
  Members: 'members',
  HIF: 'hif',
  HMP: 'hmp',
  Baseline: 'baseline',
  Conditions: 'conditions',
  'VC condition diagnosis': 'conditions',
  'Conditions Data tracking': 'conditionsDataTracking',
  PAFU: 'pafu',
  Vitals: 'vitals',
  'BP Mon': 'bp',
  'CHL Mon': 'chl',
  'DM Mon': 'dm',
  Docs: 'docs',
  NIF: 'nif',
  'Clinical Consultation': 'clinicalconsultation',
  Prescriptions: 'medications',
  'Prescriptions VC': 'medications',
  Appointments: 'appointments',
  Interactions: 'interactions',
  'HN Tasks': 'hntasks',
  'HN Meetings': 'meetings',
  'Clinical Rounds': 'clinicalrounds',
  'Nutritional Consultation': 'ncf',
  Activity: 'activity',
  Team: 'team',
  'Msg Templates': 'msgTemplates',
  'Msg Campaigns': 'msgCampaigns',
  Interventions: 'interventions',
  'Intervention Data Tracking': 'interventions_tracking',
  Milestones: 'milestones',
  NPS: 'nps',
  Accounts: 'accounts',
  'Behavior WIP': 'behaviorWip',
  'scribe baseline': 'scribeBaseline',
  'members field ids': 'memberFieldIds',
  Providers: 'providers',
  'VC request': 'vcRequest',
  'pre-baseline form scribe': 'prebaselineFormScribe',
  lifescore_latest: 'lifescore',
  'fcvd score': 'fcvd',
  'lab orders wip': 'labOrdera',
  'FCVD History': 'fcvdHistory',
  'MD Review WIP': 'mdReview',
  'Logistics Tasks': 'logisticsTasks',
  'Devices mgmt table': 'devicesManagement',
  'Logistics tasks update': 'logisticsTask',
  'Life cover': 'lifeCover',
  'Members for which risk model failed': 'memberForWhichRiskModelFailed',
  'Member tasks': 'memberTask',
  'Mental Health Consultation': 'mhc',
  'Physiotherapy Consultation': 'physio',
  'Incident reports': 'incident',
  'Member Feedback': 'member_feedback',
  'Medications Base Sync': 'medication_base',
  'Minor HIF v2': 'minorhifv2',
}

export default TABLE_ROUTES
