import AirtableField from '../../../../types/airtable-field'

const TASK_TYPES = [
  'HMP: Collect condition data',
  'Schedule HMP #1 follow-up',
  'Schedule Fitness consultation',
  'Prescribe medication',
  'Schedule Avenue visit',
  'Schedule VC consultation',
  'Schedule Home visit',
  'Flag for Internal clinical review',
  'Appointment: PAFU',
  'Reschedule call',
  'Create new content',
  'Send consultation information',
  'Schedule consultation non-Avenue specialist',
  'Send clinical summary to AHC',
  'Call Avenue',
  'Escalate member issue',
  'Refill Prescription',
  'Others',
  'Schedule HMP #2 follow-up',
  'Schedule HMP #3 follow-up',
  'Send Check-in Message #1',
  'HMP: Internal Review',
  'HMP: Send',
  'Schedule: Followup call',
  'Schedule: Avenue visit',
  'Schedule: Fitness consultation',
  'HMP: Followup',
  'Rx: Refill',
  'Nutrition: Schedule Consultation',
  'Schedule: VC consultation',
  'Schedule: non-Avenue specialist',
  'Send clinical summary',
  'Schedule: Home visit',
  'Rx: Followup',
  'Appointment: Attendance reminder',
  'Appointment: Attendance empowerment',
  'Appointment: Checkin confirmation',
  'HMP: Generate',
  'HMP: Send Monitoring Plan & Coordinate Kit Delivery',
  'HMP: Confirm Monitoring Plan and Kit Delivery ',
  'HMP: Member Review',
  'HMP: Follow',
  'HMP: Confirm Monitoring Plan and Kit Delivery',
  'Nutrition: Send Consultation Reminder',
  'Nutrition: Perform Consultation',
].sort()

const TASK_FIELDS: AirtableField[] = [
  {
    name: 'Type',
    type: 'single-select',
    options: TASK_TYPES.map((type) => ({ label: type, value: type })),
  },
  {
    name: 'Due Date',
    type: 'date',
  },
  {
    name: 'Task Priority',
    type: 'single-select',
    options: ['High', 'Medium', 'Low'].map((option) => ({
      label: option,
      value: option,
    })),
  },
  {
    name: 'Task Notes',
    type: 'long-text',
  },
  {
    name: 'Assignee',
    type: 'lookup',
    lookupUrl: 'team',
    lookupFieldNames: ['Name', 'Record ID'],
  },
  {
    name: 'Status',
    type: 'single-select',
    options: [
      'Not Started',
      'In Progress',
      'Complete',
      'On Hold',
      'Cancelled',
      'Not Applicable',
    ].map((option) => ({ label: option, value: option })),
  },
  {
    name: 'Last Status changed at',
    type: 'date',
    calculated: true,
  },
  {
    name: 'Assigned HN Name',
    type: 'lookup',
    calculated: true,
  },
]

export default TASK_FIELDS
