import { tableSchema, ColumnSchema } from '@nozbe/watermelondb'
import { CollectionType } from 'src/storage/types'

export const membersTableColumns: ColumnSchema[] = [
  { name: 'antaraId', type: 'string' },
  { name: 'first_name', type: 'string' },
  { name: 'last_name', type: 'string' },
  { name: 'middle_name', type: 'string', isOptional: true },
  { name: 'email', type: 'string' },
  { name: 'phone', type: 'string' },
  { name: 'phones', type: 'string' },
  { name: 'birth_date', type: 'string' },
  { name: 'sex', type: 'string' },
  { name: 'marital_status', type: 'string' },
  { name: 'tags', type: 'string' },
  { name: 'refused_services', type: 'string' },
  { name: 'emergency_contact', type: 'string' },
  { name: 'addresses', type: 'string' },
  { name: 'insurances', type: 'string' },
  { name: 'is_synced', type: 'boolean' },
  { name: 'employer', type: 'string' },
  { name: 'airtableRecordId', type: 'string' },
  { name: 'dependents', type: 'string' },
  { name: 'primary', type: 'string' },
  { name: 'other_dependents', type: 'string' },
  { name: 'display_name', type: 'string' },
  { name: 'intercom_url', type: 'string' },
  { name: 'assigned_hn', type: 'string' },
  { name: 'assigned_me', type: 'string' },
  { name: 'assigned_nutritionist', type: 'string' },
  { name: 'onboard_stage', type: 'string' },
  { name: 'status', type: 'string' },
  { name: 'last_synced_at', type: 'number' },
  { name: 'verification_status', type: 'string' },
  { name: 'roster_member', type: 'string' },
  { name: 'referral_source', type: 'string' },
  { name: 'registration_channel', type: 'string' },
  { name: 'payor', type: 'string' },
  { name: 'kenya_national_id', type: 'string' },
  { name: 'caregiver_contact', type: 'string' },
  { name: 'nhif_number', type: 'string' },
  { name: 'other_refused_service', type: 'string' },
  { name: 'member_cohorts', type: 'string' },
  { name: 'health_status', type: 'string' },
  { name: 'eligible_for_services', type: 'string' },
  { name: 'active_billing_package_enrollment', type: 'string' },
  { name: 'pending_billing_package_enrollment', type: 'string' },
]

export const MembersSchema = tableSchema({
  name: CollectionType.MEMBERS,
  columns: membersTableColumns,
})

export default [MembersSchema]
