name: Deploy to Prod
on:
  release:
    types: [published]

jobs:
 deploy:
  name: Deploy to Prod
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Deploy
      uses: AkhileshNS/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_email: "dev-admin@antarahealth.com"
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
